DurabilityWoodenExcavator=302 #Durability of the Wooden Excavator | default: 302
DurabilityStoneExcavator=650 #Durability of the Stone Excavator | default: 650
DurabilityIronExcavator=1300 #Durability of the Iron Excavator | default: 1300
DurabilityGoldExcavator=750 #Durability of the Gold Excavator | default: 750
DurabilityLapisExcavator=1100 #Durability of the Lapis Excavator | default: 1100
DurabilityRedstoneExcavator=1100 #Durability of the Redstone Excavator | default: 1100
DurabilityObsidianExcavator=11200 #Durability of the Obsidian Excavator | default: 11200
DurabilityDiamondExcavator=8025 #Durability of the Diamond Excavator | default: 8025
DurabilityEmeraldExcavator=9768 #Durability of the Emerald Excavator | default: 9768
DurabilityNetheriteExcavator=13675 #Durability of the Netherite Excavator | default: 13675

